### ISSUE TITLE
How to add runtime jar dependencies?

### ISSUE THREAD

**Issue by tptee** [ReadyTalk/avian#388]
Might be a stupid question, but is it possible to include jar dependencies for code targeting iOS? I'm experimenting with the hello-ios example. I can add jars to the classpath for javac, but get NoClassDefFoundErrors at runtime in the simulator.

**Comment by dicej** [comment]
By default, the hello-ios makefile uses the bootimage=true flag to build Avian, which means all the Java classes are compiled to machine code at build time instead of being just-in-time compiled at runtime.  This is because iOS disallows runtime code generation.  So if you want to add extra classes, you need to provide them at build time.  If you only need to load resources like images and properties files at runtime, you can load them from a jar at runtime, but not classes.

You can also build hello-ios using the process=interpret flag, which will produce a VM that uses bytecode interpretation at runtime instead of just-in-time compilation, but that's a lot slower.  That's your only option if you absolutely must load classes at runtime.
