### ISSUE TITLE
Avian website seems to have become nostalgic

### ISSUE THREAD

**Issue by bgould** [ReadyTalk/avian#445]
Either I am crazy, or Avian had a different looking website for a while, but has since reverted:

http://oss.readytalk.com/avian/

It is also possible that I am crazy AND the website has reverted to a previous state.

**Comment by joshuawarner32** [comment]
Yes, indeed.  TL;DR: it's fixed.

The gh-pages branch in this repository contains the correct (newer) website, but the readytalk.github.io/avian contains the old website.  This is particularly odd, since readytalk.github.io/avian hasn't changed in a while.

The only explanation I can come up with is that https://github.com/ReadyTalk/readytalk.github.io/commit/811f34ee0376576486e6d1a62d43c9433d8f8816 from @elementalvoid (which doesn't touch the website) triggered that to be re-rendered for pages, in a last-rerender-wins scenario.

I removed that directory from readytalk.github.io, but it wasn't until I pushed an empty commit to gh-pages in this repository that github actually re-rendered the site properly.

Thanks for reporting this!
